### PR TITLE
Snyk GitHub Action added

### PR DESCRIPTION
**Pull request by idvoretskyi**
Signed-off-by: Ihor Dvoretskyi <ihor@linux.com>

### CODE REVIEW

**Comment by idvoretskyi** [comment]
cc @caniszczyk 

We'll have to add the SNYK_TOKEN as a secret to the GitHub repo here.

**Comment by caniszczyk** [comment]
LGTM, token added

**Comment by hiddeco** [comment]
Possible that the action fails because the token is not accessible from a fork?

**Comment by idvoretskyi** [comment]
@hiddeco yep, we've just figured it out

**Comment by caniszczyk** [comment]
fix the DCO @idvoretskyi :)

**Comment by hiddeco** [comment]
It would also be awesome if the commits could be smashed, given this is a relative small change / addition.

**Comment by idvoretskyi** [comment]
@hiddeco yep, fixed and squashed

**Review by hiddeco — APPROVED** [review]
Thank you @idvoretskyi and @caniszczyk :100:

**Pull request merged**
