### PR TITLE
Add Paulo Gomes to maintainer's list

### PR DESCRIPTION
**Pull request by pjbgf**
Ref: https://github.com/fluxcd/community/issues/175

### CODE REVIEW

**Comment by hiddeco** [comment]
+1 from me.

@fluxcd/flux2-maintainers this is open for voting.

**Comment by darkowlzz** [comment]
+1 from me too.

**Review by makkes — APPROVED** [review]
+1! Happy to have you.

**Review by darkowlzz — APPROVED** [review]

**Review by hiddeco — APPROVED** [review]

**Review by relu — APPROVED** [review]

**Review by stefanprodan — APPROVED** [review]
+1

**Pull request merged**
