### PR TITLE
Add example podMonitor for prometheus

### PR DESCRIPTION
**Pull request by tarioch**

### CODE REVIEW

**Review by stefanprodan — CHANGES_REQUESTED** [review]
I propose we list a single object e.g.

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: source-controller
  namespace: flux-system
spec:
  namespaceSelector:
    matchNames:
      - flux-system
  selector:
    matchLabels:
      app: source-controller
  podMetricsEndpoints:
  - port: http-prom
```

And we tell people to create one for each controller they've installed.

**Comment by tarioch** [comment]
good idea, I adjusted it

**Comment by stefanprodan** [comment]
@tarioch please use my example yaml

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @tarioch 🏅

**Pull request merged**
