### PR TITLE
Update GitRepository Receiver, and Kustomization to v1

### PR DESCRIPTION
**Pull request by somtochiama**

### CODE REVIEW

**Comment by stefanprodan** [comment]
Does this PR fully includes https://github.com/fluxcd/flux2/pull/3736/files?

**Comment by somtochiama** [comment]
> Does this PR fully includes https://github.com/fluxcd/flux2/pull/3736/files?

Yes it does

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @somtochiama and @darkowlzz 🎖️

**Comment by kingdonb** [comment]
Late to the party, but I have tested this release on all 5 test clusters in my home lab and I am 👍 +1 LGTM

**Pull request merged**
