### PR TITLE
[RFC-0002] update RFC status and history

### PR DESCRIPTION
**Pull request by makkes**

### CODE REVIEW

**Review by hiddeco — CHANGES_REQUESTED** [review]
This should wait for actual release of controller. In addition, the integration is not complete in terms of functionalities. See:

- https://github.com/fluxcd/source-controller/issues/722
- https://github.com/fluxcd/source-controller/issues/723

**Comment by makkes** [comment]
Yeah, I initially thought to open only a draft PR anyway. Happy to hold this untill we're done.

**Comment by makkes** [comment]
Converted to draft

**Comment by stefanprodan** [comment]
Superseded by #2811

**Pull request closed without merging**
