### PR TITLE
Update tests/azure github.com/hashicorp/terraform-exec to v0.16.1

### PR DESCRIPTION
**Pull request by snebel29**
It closes https://github.com/fluxcd/flux2/issues/2650

- Update "github.com/hashicorp/terraform-exec" to v0.16.1
- Replace "github.com/hashicorp/terraform-exec/tfinstall" with "github.com/hashicorp/hc-install"
- Fix typos and wording in README.md

I noticed there is actually an even newer version `v0.17.2` of [github.com/hashicorp/terraform-exec](https://github.com/hashicorp/terraform-exec) with even more packages removed, and I thought It'd be easier to first move over `v0.16.1`.

### CODE REVIEW

**Comment by snebel29** [comment]
Still on draft until I can figure out how to test the change...

**Comment by snebel29** [comment]
I could not get the right `gitlib2` version (>= `v1.1.0` || <= `v1.3.0`) installed in my system 😞  to build and run `azure_test.go` successfully, I didsuccessfullyy test the new addition on isolation

<details>
  <summary>Code snipped</summary>

```go
package main

import (
	"context"
	"fmt"

	install "github.com/hashicorp/hc-install"
	"github.com/hashicorp/hc-install/fs"
	"github.com/hashicorp/hc-install/product"
	"github.com/hashicorp/hc-install/src"
)

func main() {
	i := install.NewInstaller()
	// Find Terraform binary path
	execPath, err := i.Ensure(context.TODO(), []src.Source{
		&fs.AnyVersion{Product: &product.Terraform},
	})
	fmt.Println(execPath, err)
}
```
</details>

and therefore I think it is good for review, and for the E2E test to be triggered.

**Comment by stefanprodan** [comment]
@snebel29 please run `make tidy` and force push the changes to fix the CI.

**Comment by snebel29** [comment]
> @snebel29 please run `make tidy` and force push the changes to fix the CI.

Done.

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @snebel29 🏅 

PS. Please rebase your branch with upstream main so we can merge it.

**Comment by snebel29** [comment]
> PS. Please rebase your branch with upstream main so we can merge it.

Done.

**Pull request merged**
