### PR TITLE
Update components to v0.3.0

### PR DESCRIPTION
**Pull request by relu**
Updates to use metav1.Condition type and removes references for
deprecated corev1.Condition* constants and uses the new k8s api/meta
helpers in place of the old pkg/apis/meta types.

Depends on ~fluxcd/source-controller#195~, ~https://github.com/fluxcd/notification-controller/pull/83~, ~https://github.com/fluxcd/kustomize-controller/pull/174~

### CODE REVIEW

**Comment by relu** [comment]
Needs adjustments to support https://github.com/fluxcd/kustomize-controller/pull/180, @stefanprodan I assume you're probably already working on that :hammer:.

**Comment by stefanprodan** [comment]
@relu yes going to open a PR soon

**Comment by relu** [comment]
Great, I'll rebase once you get it merged

**Review by hiddeco — APPROVED** [review]
LGTM, thank you @relu :sunflower:

**Review by stefanprodan — APPROVED** [review]
Awesome! Thanks @relu for driving this 🏅

**Pull request merged**
