### PR TITLE
feat: reconcile referencing helmchart if helmrelease is reconciled 

### PR DESCRIPTION
**Pull request by raffis**
## Current situation
`flux reconcile hr my-release --with-source` does not update the HelmChart (installed from an oci registry) if the version is a semver expression (like in this example `*`) and a new version of the chart was released meanwhile.
Meaning at the moment one has either to await the configured interval or manually annotate the referenced HelmChart in order to receive the new version.
I would expect that if I manually trigger a reconcile I get the latest version possible which is matched by semver which is not the case currently.

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-release
spec:
  chart:
    spec:
      chart: mychart
      interval: 15m0s
      sourceRef:
        kind: HelmRepository
        name: oci-repository
        namespace: flux-system
      version: '*'
  interval: 15m0s
```
## Proposal
`flux reconcile hr my-release --with-source` should actually annotate the referenced helm chart as well.

This pr implements just that:
```
go run . reconcile hr my-release --with-source
► annotating HelmRepository oci-repository in default namespace
✔ HelmRepository annotated
◎ waiting for HelmRepository reconciliation
✔ Helm repository is ready
► annotating HelmRelease my-release in default namespace
✔ HelmRelease annotated
◎ waiting for HelmRelease reconciliation
✔ applied revision 4.0.11+1
► annotating HelmChart default-my-release in flux-system namespace
✔ HelmChart annotated
◎ waiting for HelmChart reconciliation
✔ fetched revision 4.0.12+1
```

### CODE REVIEW

**Comment by stefanprodan** [comment]
IMO the chart should be reconciled before the HelmRelease as with all other sources.

**Comment by raffis** [comment]
> IMO the chart should be reconciled before the HelmRelease as with all other sources. In the case a new chart is found, the HelmRelease gets reconciled automatically so now we reconcile it twice which is wrong... cc @hiddeco

Makes sense, will change the order 👍🏻

**Comment by stefanprodan** [comment]
@raffis I suggest you first implement #3656, then call the function in there for the chart.

**Comment by raffis** [comment]
> @raffis I suggest you first implement #3656, then call the reconcileChart function in this PR.

superseded by #3675

**Pull request closed without merging**
