### PR TITLE
Add link to video review from Viktor Farcic

### PR DESCRIPTION
**Pull request by vfarcic**

### CODE REVIEW

**Review by stefanprodan — COMMENTED** [review]
Can you please add your video to the "Featured Talks" section? Thanks

**Comment by vfarcic** [comment]
Done :)

**Comment by stefanprodan** [comment]
please squash all your commits into one, signoff your commit and rebase with main.

**Comment by vfarcic** [comment]
It's done @stefanprodan

**Review by hiddeco — APPROVED** [review]
LGTM, your video also has been added to the featured resources on the https://fluxcd.io homepage :-)

**Pull request merged**
