### PR TITLE
Remove content which has moved to f/website

### PR DESCRIPTION
**Pull request by dholbach**
I was unsure about `docs/cmd` and the mentions in `Makefile`.

Eventually fixes: #1221

### CODE REVIEW

**Comment by dholbach** [comment]
Let's merge https://github.com/fluxcd/website/pull/164 first.

**Comment by stefanprodan** [comment]
We need to remove the CLI docs dir and delete the makefile targets.

**Comment by dholbach** [comment]
https://github.com/dholbach/toolkit/blob/fix-1221/docs/index.md is the last bit that hasn't been transferred. Do we want it on https://fluxcd.io/docs - related: https://github.com/fluxcd/website/issues/123 (maybe https://github.com/fluxcd/website/issues/172 too?)

**Comment by dholbach** [comment]
cf https://github.com/fluxcd/website/pull/182 - I decided to copy it over and replace the docs index

**Comment by dholbach** [comment]
Please only review after fluxcd/website#182 is done.

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @dholbach for the cleanup 🧹

**Pull request merged**
