### PR TITLE
Handle secret types properly while masking sops data

### LINKED ISSUE #2535: flux diff - failed to mask secret <name> sops data: no field named 'type'
### Describe the bug

I would like to run a `flux diff` to view the changes to be applied to our production cluster. We use SOPS secrets.

When I run `flux diff` I get the following error:

```
flux --context production diff kustomization infrastructure --path /path/to/kustomization 
✗ failed to mask secret <secret-name> sops data: no field named 'type'
```

### Steps to reproduce

1. Create a secret encrypted with SOPS.
2. Attempt to run a `flux diff` against the kustomization which has the secret encrypted with SOPS.

### Expected behavior

The flux diff should succeed.

### Screenshots and recordings

_No response_

### OS / Distro

macOS 12.2.1

### Flux version

v0.27.3

### Flux check

► checking prerequisites
✔ Kubernetes 1.21.5-eks-bc4871b >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.17.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.20.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.16.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.21.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.22.2
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.21.2
✔ all checks passed

### Git provider

_No response_

### Container Registry provider

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by aryan9600**
Fixes #2535

Signed-off-by: Sanskar Jaiswal <jaiswalsanskar078@gmail.com>

### CODE REVIEW

**Comment by souleb** [comment]
Thanks @aryan9600 for working on this. That looks good. But in issue #2535, the example given by the reporter contains the `type`, we might want to have him validate this.

**Review by souleb — APPROVED** [review]
Thanks @aryan9600 for working on this. That looks good. But in issue https://github.com/fluxcd/flux2/issues/2535, the example given by the reporter contains the type, we might want to have him validate this.

**Comment by aryan9600** [comment]
Yep, I was able to repro the issue on my local and confirm that these changes fix the issue. @nickperkins could you confirm validate it as well if possible?

**Review by hiddeco — APPROVED** [review]
This looks good to me, but is in need of a rebase. Thanks @aryan9600 :bow:

**Comment by nickperkins** [comment]
> Yep, I was able to repro the issue on my local and confirm that these changes fix the issue. @nickperkins could you confirm validate it as well if possible?

This seems to have fixed the issue on my side. Thanks!

**Pull request merged**
