### PR TITLE
Support check command with multiple config files

### PR DESCRIPTION
**Pull request by alexei-led**
Resolves: #472

### CODE REVIEW

**Review by hiddeco — COMMENTED** [review]
Hey, thank you for submitting this PR :sunflower: 

DCO sign-off is missing from your commit, and before this is added, I am unable to merge. https://github.com/fluxcd/flux2/pull/617/checks tells you how to amend your commit so that passes.

**Comment by hiddeco** [comment]
@alexei-led can you please rebase instead of merging `main` into your branch?

**Comment by alexei-led** [comment]
@hiddeco sorry, I do not understand what do you want me to do. I forked the repo committed the fix and submitted a PR. 
Please, send me commands/instructions on how to perform a rebase on open PR and keep my commits.

**Comment by alexei-led** [comment]
@hiddeco I've rebased my fork on main. signed-off/amend my commit. Hopefully, this is what you wanted, right?

**Review by hiddeco — APPROVED** [review]
LGTM, thanks for following through with my comments @alexei-led :sun_with_face:

**Pull request merged**
