### PR TITLE
[bootstrap] Make sure we reconcile with the right reconciliation method

### LINKED ISSUE #3065: flux bootstrap error after upgrading flux CLI to v0.33.0
### Describe the bug

Upgraded CLI with `brew upgrade fluxcd/tap/flux` then attempted to bootstrap the same way I do after every upgrade and receive an error:
```
✗ failed to reconcile Git repository "https://github.com/MyGitHub/flux-test": multiple errors occurred:
- PATCH https://api.github.com/repos/MyGitHub/flux-test: 400 Body should be a JSON object []
- PATCH https://api.github.com/repos/MyGitHub/flux-test: 400 Body should be a JSON object []
```

### Steps to reproduce

`brew upgrade fluxcd/tap/flux` to get the latest flux CLI version, then attempt a cluster upgrade:
```
flux bootstrap github \
        --owner=MyGitHub \
        --repository=flux-test \
        --read-write-key \
        --reconcile \
        --branch=master \
        --path=cluster \
        --components-extra=image-reflector-controller,image-automation-controller
```

### Expected behavior

Flux components on the cluster would be upgraded and any required changes committed back to git.

### Screenshots and recordings

_No response_

### OS / Distro

macOS 12.3.1

### Flux version

v0.33.0

### Flux check

```► checking prerequisites
✔ Kubernetes 1.21.13-eks-84b4fe6 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.22.2
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.24.1
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.20.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.27.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.25.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.26.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta1
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta1
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta1
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta1
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta1
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed
```

### Git provider

_No response_

### Container Registry provider

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by souleb**
fixes #3065 

Signed-off-by: Soule BA <soule@weave.works>

### CODE REVIEW

**Comment by souleb** [comment]
> @souleb is this related to #3065?

yes it is.

**Comment by stefanprodan** [comment]
Ok so let's ask the people who reported the issue to test this before we merge it. Our e2e tests work fine without this change, so we have no means of validating this PR on our own.

**Comment by souleb** [comment]
@hiddeco the bug described in https://github.com/fluxcd/go-git-providers/issues/67 might be fixed with the change I introduced in the way we patch repository for github. Can you confirm this?

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @souleb 🏅

**Pull request merged**
