### PR TITLE
all: fix some typos

### PR DESCRIPTION
**Pull request by cuishuang**

### CODE REVIEW

**Review by dholbach — APPROVED** [review]
Thanks a lot for the PR @cuishuang !

**Comment by hiddeco** [comment]
This needs a sign-off before it can be merged @cuishuang. If you do `git commit --amend --signoff` and a force push, it should be good to go :-)

**Comment by cuishuang** [comment]
> This needs a sign-off before it can be merged @cuishuang. If you do `git commit --amend --signoff` and a force push, it should be good to go :-)

Done ^_^

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @cuishuang

**Pull request merged**
