### PR TITLE
Remove resourceNames in integration secrets

### PR DESCRIPTION
**Pull request by NissesSenap**
* Fixes: #1524
* We remove resourceName due to the following:
  Note: You cannot restrict create or deletecollection requests by resourceName.
  For create, this limitation is because the object name is not known at authorization time.
* Fix typo in azure-registry cronjob
Signed-off-by: Edvin Norling <edvin.norling@xenit.se>

### CODE REVIEW

**Comment by NissesSenap** [comment]
ping @molszews

**Comment by NissesSenap** [comment]
This is only a issue in the deployment solution, if you use a cronjob it will be checked when the job is created.
I can't come up with a good solution to be able to use a specific secret in the deployment solution and still have it as a variabel.

We could of course use a hard corded variabel name, and then we shouldn't get this issue if I understand the error correctly.

**Comment by stefanprodan** [comment]
@NissesSenap please rebase instead of merge.

**Comment by NissesSenap** [comment]
Sure I will remember that for the future. Thanks @stefanprodan

**Review by stefanprodan — APPROVED** [review]
LGTM 

Thanks @NissesSenap ☕

**Pull request merged**
