### PR TITLE
Fix: Cluster-Dashboard variable missing datasource

### PR DESCRIPTION
**Pull request by mlashley**
Signed-off-by: Malcolm Lashley <mlashley@gmail.com>

### CODE REVIEW

**Comment by kingdonb** [comment]
Thank you for contributing this!

Can you comment or provide a screenshot about what the effect of this missing data source is to the end user?

**Comment by kingdonb** [comment]
(It looks like this one is superseded by #2727)

**Comment by mlashley** [comment]
> Can you comment or provide a screenshot about what the effect of this missing data source is to the end user?

Sorry - I didn't take a screenshot - and my updated version is already deployed to my cluster - but the 'namespace' dashboard variable  wasn't populated for me without it... there is no 'custom all value' - and the default (at least in Grafana I was using) is to `x|y|z|...` all the values for 'all' - with the net result that all the promql using `gotk_blah{xxx="$namespace"}` failed to match any labels. I see that #2727 has included my change too.

**Comment by kingdonb** [comment]
Thanks for the elaboration, that helps! 👍

I will give this a try later this week if someone else does not get to it first. This should get merged no problem. Thanks for your contribution here.

**Comment by mlashley** [comment]
This has since been fixed in #2727 - we should close this one.

**Pull request closed without merging**
