### PR TITLE
update Deleting old resources CRD

### PR DESCRIPTION
**Pull request by pratikbalar**
update Deleting old resources CRD

### CODE REVIEW

**Review by hiddeco — APPROVED** [review]

**Comment by hiddeco** [comment]
@pratikbalar we require a sign-off on commits, the instructions for this can be found here: https://github.com/fluxcd/flux2/pull/561/checks?check_run_id=1511652674.

**Comment by pratikbalar** [comment]
Sure I'll do it in the morning, (after 10 hours)

**Comment by pratikbalar** [comment]
it say's this while pushing, i have enable 2FA so using personal token as password. username and token are correct.
image

**Comment by stefanprodan** [comment]
You need to clone your fork

**Comment by pratikbalar** [comment]
so i have to close this, forked flux2 make changes and create PR right?

**Pull request closed without merging**
