### PR TITLE
Fix selection of kustomization resource from multi doc yaml

### PR DESCRIPTION
**Pull request by mraerino**
Fixes https://github.com/fluxcd/flux2/issues/4132

### CODE REVIEW

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @mraerino, please squash and rebase with main.

**Comment by mraerino** [comment]
i don't have merge privileges in this repo, you need to merge it

**Comment by mraerino** [comment]
i suspected you meant the `squash` merge method. or do you expect me to rewrite the branch so you can fast-forward merge?

**Comment by hiddeco** [comment]
The latter: squash into a single commit and rebase with `main`, so it can be merged :-).

**Review by hiddeco — APPROVED** [review]

**Pull request merged**
