### PR TITLE
Add @relu to maintainers list

### PR DESCRIPTION
**Pull request by relu**
Self-Promotion is the best promotion :blush:

### CODE REVIEW

**Review by hiddeco — APPROVED** [review]
+:100:

**Review by stefanprodan — APPROVED** [review]
Thank you @relu for all your contributions! I am very happy to welcome you to Flux maintainers team.

**Review by squaremo — APPROVED** [review]
Non-binding, but nevertheless I approve -- welcome @relu !

**Comment by relu** [comment]
Proud to join such a nice bunch! Thank you :bow:

**Pull request merged**
