### PR TITLE
Add GPG signing to Github/Gitlab/Bitbucket bootstrap

### PR DESCRIPTION
**Pull request by robwittman**
Signed-off-by: Robert Wittman <robkwittman@gmail.com>

### CODE REVIEW

**Comment by Chili-Man** [comment]
We ran into this issue trying to bootstrap flux with gpg signing keys; I have tried this version and confirmed that it works

**Review by hiddeco — COMMENTED** [review]
Thank you for your contribution :bow: 

It looks like we simply forgot to add the flags to the non-plain bootstrap providers when we introduced this feature. Therefore, if you feel up for it, it would be very welcome to also add them to the remaining providers (GitLab and BitBucket). 

In addition, the PR requires a rebase on `main` (opposed to merging `main` -> this branch).

**Comment by robwittman** [comment]
GPG flags are now being passed to all of Github, GitLab, and BitBucket :)

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @robwittman 🏅

**Pull request merged**
