### PR TITLE
Edit grafana dashboard to be able to filter by namespace

### PR DESCRIPTION
**Pull request by drazul**
Add new variable to filter by exported namespace.

Edit definition of namespace variable to use grafana custom promql function `label_values`.
Rename variable namespace to operator_namespace.
Rename variable exported_namespace to namespace

Signed-off-by: Daniel AguadoAraujo <daniel.aguadoaraujo@gfk.com>

### CODE REVIEW

**Review by dminca — APPROVED** [review]
lgtm 👍

**Comment by stefanprodan** [comment]
> Rename variable namespace to operator_namespace.
> Rename variable exported_namespace to namespace

I understand the changes but not the reason for them, what are you trying to achieve here?

**Comment by drazul** [comment]
> > Rename variable namespace to operator_namespace.
> > Rename variable exported_namespace to namespace
> 
> I understand the changes but not the reason for them, what are you trying to achieve here?

In this context the operator namespace only matter if we have more than one operator running in the same cluster, and the name 'exported_namespace' has meaning only because namespace variable name is already in use.

In my opinion renaming both variables add a better understanding about the dashboard to not technical people.

But I can keep both variables as they are written in the prometheus metric if you want.

**Comment by stefanprodan** [comment]
> In my opinion renaming both variables add a better understanding about the dashboard to not technical people.

Thanks, now I get it.

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @drazul can you please rebase with upstream main and force push.

**Comment by drazul** [comment]
> LGTM
> 
> Thanks @drazul can you please rebase with upstream main and force push.

Done

**Pull request merged**
