### PR TITLE
Added Jan 25 Meetup to Upcoming Events section

### PR DESCRIPTION
**Pull request by staceypotter**
Signed-off-by: Stacey Potter <50154848+staceypotter@users.noreply.github.com>

### CODE REVIEW

**Review by hiddeco — APPROVED** [review]

**Comment by staceypotter** [comment]
@hiddeco is there anything else I need to do for this? Thanks!

**Comment by hiddeco** [comment]
For some reason the tests weren't triggered @staceypotter, rebased and pushed from local machine to re-trigger them.

**Pull request merged**
