### PR TITLE
docs: add a missing git pull command

### PR DESCRIPTION
**Pull request by sano307**
After automatically committed (via `flux <GITHUB_USER@users.noreply.github.com>`) to remote repository through bootstrap command, it is necessary to be synchronized locally.

### CODE REVIEW

**Comment by stefanprodan** [comment]
The pull command doesn't make sense here IMO, you need to clone the repo first. Have you followed the guide? the clone+pull is right below.

**Comment by sano307** [comment]
> you need to clone the repo first.

Oh, really? I didn't find a message to clone a specific repository, so I created a `flux2-demo` private repository in my GitHub account and executed bootstrap command.

```console
$ flux bootstrap github \
  --owner=$GITHUB_USER \
  --repository=fluxcd2-demo \
  --branch=main \
  --path=test-cluster \
  --personal
```

And then, `07b9224` and `76d97c5` were automatically committed via `flux <GITHUB_USER@users.noreply.github.com>`.

```console
commit 76d97c5e1b41ac90477f62077888973a16de71a1
Author: flux <sano307@users.noreply.github.com>
Date:   Sat Nov 21 12:26:07 2020 +0900

    Add manifests

commit 07b92248112afb047a17fe3cc82826ce46488012
Author: flux <sano307@users.noreply.github.com>
Date:   Sat Nov 21 12:25:29 2020 +0900

    Add manifests

commit f716d66e1aeb53c7df66d761f4479d1a02accc10
Author: Inseo Kim <sano307@naver.com>
Date:   Sat Nov 21 12:22:16 2020 +0900

    bootstrap: initial
```

If my method is wrong, could you close this pull request? Thank you for comment. :bow:

**Comment by stefanprodan** [comment]
Flux bootstrap creates the repository for you, the clone command is here https://toolkit.fluxcd.io/get-started/#staging-workflow. Now if you want to create the repo manually, then yes you can pull it after bootstrap, but that's not what the "get started guide" shows.

**Comment by sano307** [comment]
> Flux bootstrap creates the repository for you

I didn't know this. Awesome!

> but that's not what the "get started guide" shows.

Yes, I totally agree.

**Pull request closed without merging**
