### PR TITLE
Add e2e sequence diagrams

### PR DESCRIPTION
**Pull request by stefanprodan**
Add end-to-end sequence diagrams made with Mermaid for:
- Cluster sync from Git
- Helm release upgrade from Git
- Image update to Git

Ref: https://github.com/fluxcd/website/pull/725

flux-cluster-sync
flux-helm-upgrade
flux-image-update

### CODE REVIEW

**Review by makkes — APPROVED** [review]
I love visualizations! Those will help people grasp Flux much quicker. Don't we want to include those in the official docs, too?

**Comment by stefanprodan** [comment]
@makkes I made these for https://github.com/fluxcd/website/pull/725, @kingdonb we'll have to figure out how to enable Mermaid rendering with Hugo.

**Comment by mbovo** [comment]
Sorry to inject in to the converstaion, I think you should add the mermaid.js to the hugo template, I'll try to prepare a PR (as soon as find where that code lives :D )
```
<script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
<script>mermaid.initialize({ startOnLoad: true, securityLevel: 'loose'}});</script>
```

**Comment by kranurag7** [comment]
@stefanprodan These visualizations are really superb.

**Comment by kingdonb** [comment]
Awesome, thank you! This will make a great addition to the E2E doc 👍

**Comment by stefanprodan** [comment]
@kingdonb looks like Hugo has a shortcode for mermaid https://learn.netlify.app/en/shortcodes/mermaid/ So instead of using code blocks like in here we could use `{{< mermaid >}}` for the website.

**Pull request merged**
