### PR TITLE
Refactor test helpers

### PR DESCRIPTION
**Pull request by stefanprodan**
Changes:
- move test helpers to main
- add support for inline golden values
- add test for `flux --version`

### CODE REVIEW

**Review by hiddeco — COMMENTED** [review]
- [x] Thank you Stefan 🙏

**Review by hiddeco — APPROVED** [review]

**Comment by allenporter** [comment]
Thanks, I had a similar PR in mind with some follow up improvements.

**Comment by stefanprodan** [comment]
Oh one more thing, the test helpers are using `ioutil` this needs to go away, see https://github.com/fluxcd/flux2/issues/1658

**Comment by allenporter** [comment]
Thanks, I was browsing issues and saw that and realized, I'll send a fix.

**Comment by allenporter** [comment]
Moving to TestMain sounds good, will do. I'm assuming all tests that have times/dates in the golden files will need that setup -- that is a `TestMain` per test file. Is that right?

**Comment by allenporter** [comment]
I realize now, TestMain can do setup and teardown to handle restoring any environment variables

**Pull request merged**
